# Generated by Django 5.2.7 on 2025-12-21 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('contenu', models.TextField()),
                ('type_notification', models.CharField(choices=[('communique', 'Communiqué'), ('note', 'Note'), ('absence', 'Absence'), ('bulletin', 'Bulletin')], max_length=50)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('notification', 'Notification interne')], max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echoue', 'Échoué'), ('lu', 'Lu')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='messagerie.notification')),
            ],
            options={
                'unique_together': {('notification', 'destinataire')},
            },
        ),
    ]
