# Generated by Django 5.2.7 on 2025-12-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, null=True)),
                ('niveau', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='canal',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('notification', 'Notification interne')], max_length=30),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone_parent', models.CharField(max_length=15)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='messagerie.classe')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationtarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationtarget',
            name='eleve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messagerie.eleve'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notificationtarget',
            unique_together={('notification', 'eleve')},
        ),
        migrations.RemoveField(
            model_name='notificationtarget',
            name='destinataire',
        ),
    ]
