from .classe import ClasseSerializer
from .eleve import EleveWriteSerializer, EleveReadSerializer
from .notification import NotificationWriteSerializer, NotificationReadSerializer
from .notification_target import NotificationTargetSerializer